export { Signup } from './Signup'
export { Login } from './Login'
export { Admin } from './Admin'
export { Home } from './Home'
export { Movies  } from './Peliculas'
export { Series } from './Series'
export { Detail } from './Detail'
export { Users } from './Users'